/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package tcc;

import java.util.logging.Level;
import java.util.logging.Logger;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;


/**
 *
 * @author Henrique
 */
public class MensReport extends javax.swing.JDialog {

    /**
     * Creates new form MensReport
     */
    char tipo = '0';
        
    public MensReport(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btBotao = new javax.swing.JButton();
        tfMensagem = new javax.swing.JTextField();
        ProgBar = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gerador de Relatórios do Silo");
        setAlwaysOnTop(true);
        setModal(true);
        setModalityType(java.awt.Dialog.ModalityType.DOCUMENT_MODAL);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tcc/Imagens/impressora128x128.png"))); // NOI18N

        btBotao.setText("Cancelar");
        btBotao.setIconTextGap(10);
        btBotao.setMaximumSize(new java.awt.Dimension(109, 38));
        btBotao.setMinimumSize(new java.awt.Dimension(109, 38));
        btBotao.setPreferredSize(new java.awt.Dimension(109, 38));
        btBotao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btBotaoMousePressed(evt);
            }
        });
        btBotao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btBotaoKeyPressed(evt);
            }
        });

        tfMensagem.setEditable(false);
        tfMensagem.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfMensagem.setText("Gerando Relatório...");

        ProgBar.setIndeterminate(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(btBotao, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 47, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfMensagem)
                    .addComponent(ProgBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(76, 76, 76))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(0, 0, 0)
                .addComponent(tfMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ProgBar, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btBotao, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btBotaoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btBotaoMousePressed
        AcaoBotao();
    }//GEN-LAST:event_btBotaoMousePressed

    private void btBotaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btBotaoKeyPressed
        if(evt.getKeyCode()==10){
            AcaoBotao();
        }
    }//GEN-LAST:event_btBotaoKeyPressed

    public void setMensagem(String msg) {
        tfMensagem.setText(msg);
    }
    
    public void Mostrar(JasperPrint jp){
        JasperViewer.viewReport(jp,false);
        btBotao.setText("Ok");
        tipo='1';
        ProgBar.setIndeterminate(false);
        ProgBar.setValue(100);
        ProgBar.setString("100%");
        ProgBar.setStringPainted(true);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar ProgBar;
    private javax.swing.JButton btBotao;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField tfMensagem;
    // End of variables declaration//GEN-END:variables

    private void AcaoBotao() {
        if(tipo==0){
            try {
                Relatorios.handle.cancellFill();
            } catch (JRException ex) {
                Logger.getLogger(MensReport.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            this.dispose();
        }
    }
}
